site:
  name: 二咪的四时漫录
  site: 'https://2me.fun'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: 二咪的四时漫录
    template: '%s — 二咪的四时漫录'
  description: "一只懒猫记录生活点滴的笔记簿，分享一些有趣的事情，也许会有一些技术文章和实用工具。"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 二咪的四时漫录
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: zh-cn
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
